/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import dao.GiamgiaDAO;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Giamgia;


/**
 *
 * @author hungmetan
 */
public class AddMagiamgia extends javax.swing.JDialog {
    private MagiamgiaForm owner;
    /**
     * Creates new form AddMagiamgia
     */
        public AddMagiamgia(javax.swing.JInternalFrame parent, javax.swing.JFrame owner, boolean modal) {
        super(owner, modal);
        this.owner = (MagiamgiaForm) parent;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbxLoaisp = new javax.swing.JComboBox<>();
        btnAddMagiamgia = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtPhantramgiam = new javax.swing.JTextField();
        dateNgayketthuc = new com.toedter.calendar.JDateChooser();
        dateNgaybatdau = new com.toedter.calendar.JDateChooser();
        cbxTrangthai = new javax.swing.JComboBox<>();
        txtMota = new javax.swing.JTextField();
        txtMagiamgia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("MÃ GIẢM GIÁ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("NGÀY BẮT ĐẦU");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 130, -1));

        jLabel10.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Loại sản phẩm");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        cbxLoaisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn loại sản phẩm--", "Thực phẩm", "Đồ gia dụng", "Mỹ phẩm", "Văn phòng phẩm", "Đồ dùng cá nhân", " " }));
        cbxLoaisp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLoaispItemStateChanged(evt);
            }
        });
        cbxLoaisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaispActionPerformed(evt);
            }
        });
        cbxLoaisp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxLoaispPropertyChange(evt);
            }
        });
        jPanel1.add(cbxLoaisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 209, 32));

        btnAddMagiamgia.setBackground(new java.awt.Color(0, 0, 153));
        btnAddMagiamgia.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        btnAddMagiamgia.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMagiamgia.setText("THÊM");
        btnAddMagiamgia.setBorder(null);
        btnAddMagiamgia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddMagiamgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMagiamgiaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddMagiamgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 160, 35));

        btnCancel.setBackground(new java.awt.Color(0, 0, 153));
        btnCancel.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Huỷ bỏ");
        btnCancel.setBorder(null);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 140, 35));

        jPanel3.setLayout(new java.awt.CardLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 84, -1, -1));

        jLabel15.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("PHẦN TRĂM GIẢM");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 150, -1));

        txtPhantramgiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhantramgiamActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhantramgiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 189, 33));
        jPanel1.add(dateNgayketthuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 210, 30));
        jPanel1.add(dateNgaybatdau, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 210, 30));

        cbxTrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn trạng thái--", "Khả dụng", "Không khả dụng" }));
        jPanel1.add(cbxTrangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 210, 30));
        jPanel1.add(txtMota, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 210, 30));
        jPanel1.add(txtMagiamgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 190, 30));

        jLabel12.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("MÔ TẢ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Trạng thái");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("NGÀY KẾT THÚC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 140, -1));

        jLabel16.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("THÊM MÃ GIẢM GIÁ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/sRKbEzd.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -230, 780, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxLoaispItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLoaispItemStateChanged

    }//GEN-LAST:event_cbxLoaispItemStateChanged

    private void cbxLoaispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaispActionPerformed

    private void cbxLoaispPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxLoaispPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaispPropertyChange

    private void btnAddMagiamgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMagiamgiaActionPerformed
        // TODO add your handling code here:
                try {
            String Magiamgia = txtMagiamgia.getText().trim();
            String Loaisp = cbxLoaisp.getSelectedItem().toString();
            int Phantramgiam = Integer.parseInt(txtPhantramgiam.getText().trim());
            java.util.Date ngaybatdauUtil = dateNgaybatdau.getDate();
            if (ngaybatdauUtil == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày bắt đầu!");
                return;
            }
            java.sql.Date Ngaybatdau = new java.sql.Date(ngaybatdauUtil.getTime());

            java.util.Date ngayketthucUtil = dateNgayketthuc.getDate();
            if (ngayketthucUtil == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày kết thúc!");
                return;
            }
            java.sql.Date Ngayketthuc = new java.sql.Date(ngayketthucUtil.getTime());
            String Mota = txtMota.getText().trim();
            int Trangthai = cbxTrangthai.getSelectedItem().toString().equalsIgnoreCase("Khả dụng") ? 1 : 0;

            Giamgia gg = new Giamgia(Magiamgia, Loaisp, Phantramgiam, Ngaybatdau, Ngayketthuc, Mota,Trangthai);

            int inserted = GiamgiaDAO.getInstance().insert(gg);
            if (inserted > 0) {
                JOptionPane.showMessageDialog(this, "Thêm mã giảm giá thành công!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Phần trăm giảm phải là số hợp lệ!");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi thêm mã giảm giá.");
        }

    }//GEN-LAST:event_btnAddMagiamgiaActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtPhantramgiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhantramgiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhantramgiamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMagiamgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMagiamgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMagiamgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMagiamgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
               java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddMagiamgia dialog = new AddMagiamgia(null, new JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMagiamgia;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cbxLoaisp;
    private javax.swing.JComboBox<String> cbxTrangthai;
    private com.toedter.calendar.JDateChooser dateNgaybatdau;
    private com.toedter.calendar.JDateChooser dateNgayketthuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtMagiamgia;
    private javax.swing.JTextField txtMota;
    private javax.swing.JTextField txtPhantramgiam;
    // End of variables declaration//GEN-END:variables
}
