/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.NhaCungCapDAO;
import dao.SanphamDAO;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Sanpham;


public class AddProduct extends javax.swing.JDialog {
private String selectedImagePath = null; 

    private ProductForm owner;

    public AddProduct(javax.swing.JInternalFrame parent, javax.swing.JFrame owner, boolean modal) {
        super(owner, modal);
        this.owner = (ProductForm) parent;
        initComponents();
        setLocationRelativeTo(null);
        loadManccToComboBox();
        String nextMasp = SanphamDAO.getInstance().generateNextMasp();
        txtMasp.setText(nextMasp);
        txtMasp.setEditable(false); 
    }
    private void loadManccToComboBox() {
    ArrayList<String> list = NhaCungCapDAO.getInstance().getAllManccDisplay();
    cbxMancc.removeAllItems();
    cbxMancc.addItem("--Chọn nhà cung cấp--");
    for (String display : list) {
        cbxMancc.addItem(display);
    }
}

    private AddProduct(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTensp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDonvitinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGianhap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGiaban = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAddPicture = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cbxLoaisp = new javax.swing.JComboBox<>();
        btnAddProduct = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        dateHansudung = new com.toedter.calendar.JDateChooser();
        dateNgaysanxuat = new com.toedter.calendar.JDateChooser();
        cbxTrangthai = new javax.swing.JComboBox<>();
        cbxMancc = new javax.swing.JComboBox<>();
        txtGhichu = new javax.swing.JTextField();
        txtMasp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm sản phẩm mới");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Mã sản phẩm");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Tên sản phẩm");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel1.add(txtTensp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 32));

        jLabel4.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Đơn vị tính");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, -1));
        jPanel1.add(txtDonvitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 32));

        jLabel6.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Giá nhập");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 90, -1));
        jPanel1.add(txtGianhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 150, 32));

        jLabel7.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Giá bán");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 70, -1));
        jPanel1.add(txtGiaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 150, 32));

        jLabel8.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Mã nhà cung cấp");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 140, -1));

        jLabel9.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Ngày sản xuất");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        btnAddPicture.setText("Chọn");
        btnAddPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPictureActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Loại sản phẩm");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        cbxLoaisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn loại sản phẩm--", "Thực phẩm", "Đồ gia dụng", "Mỹ phẩm", "Văn phòng phẩm", "Đồ dùng cá nhân", " " }));
        cbxLoaisp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLoaispItemStateChanged(evt);
            }
        });
        cbxLoaisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaispActionPerformed(evt);
            }
        });
        cbxLoaisp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxLoaispPropertyChange(evt);
            }
        });
        jPanel1.add(cbxLoaisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 170, 32));

        btnAddProduct.setBackground(new java.awt.Color(0, 0, 153));
        btnAddProduct.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("Thêm sản phẩm");
        btnAddProduct.setBorder(null);
        btnAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 140, 35));

        btnCancel.setBackground(new java.awt.Color(0, 0, 153));
        btnCancel.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Huỷ bỏ");
        btnCancel.setBorder(null);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 140, 35));

        jPanel3.setLayout(new java.awt.CardLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 84, -1, -1));

        jLabel15.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("Số lượng");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, -1));

        txtSoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoluongActionPerformed(evt);
            }
        });
        jPanel1.add(txtSoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 33));
        jPanel1.add(dateHansudung, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 170, 30));
        jPanel1.add(dateNgaysanxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 170, 30));

        cbxTrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn trạng thái--", "Đang bán", "Ngưng bán" }));
        jPanel1.add(cbxTrangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 170, 30));

        cbxMancc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn nhà cung cấp--" }));
        jPanel1.add(cbxMancc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 150, 30));
        jPanel1.add(txtGhichu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 170, 30));
        jPanel1.add(txtMasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 30));

        jLabel13.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Ảnh sản phẩm");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Ghi chú");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Trạng thái");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Hạn sử dụng");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        jLabel16.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("THÊM SẢN PHẨM MỚI");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel14);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 180, 220));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/sRKbEzd.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -230, 1150, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxLoaispItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLoaispItemStateChanged
     
    }//GEN-LAST:event_cbxLoaispItemStateChanged

    private void cbxLoaispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaispActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
       try {
        String Masp = txtMasp.getText().trim();
        String Tensp = txtTensp.getText().trim();
        String Donvitinh = txtDonvitinh.getText().trim();
        int Soluong = Integer.parseInt(txtSoluong.getText().trim());

        double Gianhap = Double.parseDouble(txtGianhap.getText().trim());
        double Giaban = Double.parseDouble(txtGiaban.getText().trim());

        String Loaisp = cbxLoaisp.getSelectedItem().toString();
        String selected = cbxMancc.getSelectedItem().toString();
        String Mancc = selected.split(" - ")[0];
     
        String Ghichu = txtGhichu.getText().trim();

        java.util.Date ngaysanxuatUtil = dateNgaysanxuat.getDate();
        if (ngaysanxuatUtil == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sản xuất!");
            return;
        }
        java.sql.Date Ngaysanxuat = new java.sql.Date(ngaysanxuatUtil.getTime());

        java.util.Date hansudungUtil = dateHansudung.getDate();
        if (hansudungUtil == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hạn sử dụng!");
            return;
        }
        
         if (!ngaysanxuatUtil.before(hansudungUtil)) {
        JOptionPane.showMessageDialog(this, "Ngày sản xuất phải trước hơn hạn sử dụng!");
        return;
    }
        java.sql.Date Hansudung = new java.sql.Date(hansudungUtil.getTime());

        int Trangthai = cbxTrangthai.getSelectedItem().toString().equalsIgnoreCase("Đang bán") ? 1 : 0;
  String anhPathToSave = null;
        if (selectedImagePath != null) {
            try {
                anhPathToSave = saveImageToAppFolder(selectedImagePath, Masp);
            } catch (Exception ex) {
                ex.printStackTrace();
            
                anhPathToSave = selectedImagePath;
            }
        }
        Sanpham sp = new Sanpham(Masp, Tensp,anhPathToSave, Donvitinh, Soluong, Gianhap, Giaban,
                Ngaysanxuat, Hansudung,Loaisp, Mancc, Trangthai ,Ghichu );

        int inserted = SanphamDAO.getInstance().insert(sp);
        if (inserted > 0) {
            JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!");
            this.dispose(); 
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Số lượng, giá nhập hoặc giá bán phải là số hợp lệ!");
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi thêm sản phẩm.");
    }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtSoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoluongActionPerformed

    private void cbxLoaispPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxLoaispPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxLoaispPropertyChange

    private void btnAddPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPictureActionPerformed
   JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Chọn ảnh sản phẩm");
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    javax.swing.filechooser.FileNameExtensionFilter filter =
            new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif", "bmp");
    chooser.setFileFilter(filter);

    int result = chooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        String srcPath = chooser.getSelectedFile().getAbsolutePath();
        int w = jPanel2.getWidth() - 6;
        int h = jPanel2.getHeight() - 6;
        ImageIcon icon = new ImageIcon(new ImageIcon(srcPath).getImage().getScaledInstance(
                w > 0 ? w : 150, h > 0 ? h : 150, Image.SCALE_SMOOTH));
        jLabel14.setIcon(icon);

        String masp = txtMasp.getText() != null ? txtMasp.getText().trim() : "";
        if (masp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm rỗng. Vui lòng tạo mã trước khi lưu ảnh.");
            return;
        }
        String saved = saveImageToAppFolder(srcPath, masp);
        if (saved != null) {
            this.selectedImagePath = saved; 
            System.out.println("Ảnh đã lưu: " + saved);
        }

    }
    }//GEN-LAST:event_btnAddPictureActionPerformed

private String saveImageToAppFolder(String imagePath, String masp) {
    try {
        if (imagePath == null || masp == null || masp.isEmpty()) return null;
        java.nio.file.Path destDir = java.nio.file.Paths.get(System.getProperty("user.dir"), "images");
        if (!java.nio.file.Files.exists(destDir)) {
            java.nio.file.Files.createDirectories(destDir);
        }
        String ext = "";
        int i = imagePath.lastIndexOf('.');
        if (i >= 0) ext = imagePath.substring(i); // ".jpg"
        String newFileName = masp + ext;
        java.nio.file.Path dest = destDir.resolve(newFileName);
        java.nio.file.Files.copy(
            java.nio.file.Paths.get(imagePath),
            dest,
            java.nio.file.StandardCopyOption.REPLACE_EXISTING
        );
        return dest.toString();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi lưu ảnh: " + e.getMessage());
        return null;
    }
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddProduct dialog = new AddProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPicture;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cbxLoaisp;
    private javax.swing.JComboBox<String> cbxMancc;
    private javax.swing.JComboBox<String> cbxTrangthai;
    private com.toedter.calendar.JDateChooser dateHansudung;
    private com.toedter.calendar.JDateChooser dateNgaysanxuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDonvitinh;
    private javax.swing.JTextField txtGhichu;
    private javax.swing.JTextField txtGiaban;
    private javax.swing.JTextField txtGianhap;
    private javax.swing.JTextField txtMasp;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTensp;
    // End of variables declaration//GEN-END:variables
}
