/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.WritePDF;
import dao.AccountDAO;
import dao.ChiTietPhieuNhapDAO;
import dao.ChiTietPhieuXuatDAO;
import dao.SanphamDAO;
import dao.NhaCungCapDAO;
import dao.PhieuNhapDAO;
import dao.PhieuXuatDAO;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.ChiTietPhieuNhap;
import model.ChiTietPhieuXuat;
import model.Phieu;
import model.PhieuNhap;
import model.PhieuXuat;


public class CTThongKe extends javax.swing.JDialog {

    /**
     * Creates new form CTPhieuDialog
     */
    private ThongKeForm parent;

    public CTThongKe(javax.swing.JInternalFrame parent, javax.swing.JFrame owner, boolean modal) {
        super(owner, modal);
        this.parent = (ThongKeForm) parent;
        initComponents();
        setLocationRelativeTo(null);
        Phieu pn = this.parent.findPhieu();
        labelMaPhieu.setText(pn.getMaphieu());
        labelNguoiTao.setText(AccountDAO.getInstance().selectById(pn.getNguoitao()).getFullName());
        labelTongTien.setText(this.parent.getFormatter().format(pn.getTongtien()) + "đ");
        labelThoiGianTao.setText(this.parent.getFormatDate().format(pn.getThoigiantao()));
        loadDataToTableProduct();
        setWidthTable();
    }

    public void setWidthTable() {
        tblChiTietPhieu.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblChiTietPhieu.getColumnModel().getColumn(1).setPreferredWidth(10);
        tblChiTietPhieu.getColumnModel().getColumn(2).setPreferredWidth(250);
    }

    public void loadDataToTableProduct() {
        try {
            DefaultTableModel tblCTPhieumd = (DefaultTableModel) tblChiTietPhieu.getModel();
            tblCTPhieumd.setRowCount(0);
            Phieu pn = this.parent.findPhieu();
            String check = pn.getMaphieu();
            if (check.contains("PX")) {
                ArrayList<ChiTietPhieuXuat> CTPhieu = ChiTietPhieuXuatDAO.getInstance().selectAll(check);
                for (int i = 0; i < CTPhieu.size(); i++) {
                    tblCTPhieumd.addRow(new Object[]{
                        i + 1,
                        CTPhieu.get(i).getMasp(),
                        SanphamDAO.getInstance().selectById(CTPhieu.get(i).getMasp()).getTensp(),
                        CTPhieu.get(i).getSoluong(),
                        parent.getFormatter().format(CTPhieu.get(i).getGiaban()) + "đ",
                        parent.getFormatter().format(CTPhieu.get(i).getGiaban() * CTPhieu.get(i).getSoluong()) + "đ"
                    });
                }
            } else {
                ArrayList<ChiTietPhieuNhap> CTPhieu = ChiTietPhieuNhapDAO.getInstance().selectAll(check);
                for (int i = 0; i < CTPhieu.size(); i++) {
                    tblCTPhieumd.addRow(new Object[]{
                        i + 1,
                        CTPhieu.get(i).getMasp(),
                        SanphamDAO.getInstance().selectById(CTPhieu.get(i).getMasp()).getTensp(),
                        CTPhieu.get(i).getSoluong(),
                        parent.getFormatter().format(CTPhieu.get(i).getGianhap()) + "đ",
                        parent.getFormatter().format(CTPhieu.get(i).getGianhap() * CTPhieu.get(i).getSoluong()) + "đ"
                    });
                }
            }

        } catch (Exception e) {
        }
    }

    public ArrayList<Phieu> getPhieuAll() {
        ArrayList<Phieu> result = new ArrayList<>();
        ArrayList<PhieuNhap> conten1 = PhieuNhapDAO.getInstance().selectAll();
        ArrayList<PhieuXuat> conten2 = PhieuXuatDAO.getInstance().selectAll();
        for (PhieuNhap phieunhap : conten1) {
            String Maphieu = phieunhap.getMaphieu();
            Timestamp Thoigiantao = phieunhap.getThoigiantao();
            String Nguoitao = phieunhap.getNguoitao();
            double Tongtien = phieunhap.getTongtien();
            Phieu ac = new Phieu(Maphieu,Thoigiantao, Nguoitao, Tongtien);
            result.add(ac);
        }
        for (PhieuXuat phieuxuat : conten2) {
            String Maphieu = phieuxuat.getMaphieu();
            Timestamp Thoigiantao = phieuxuat.getThoigiantao();
            String Nguoitao = phieuxuat.getNguoitao();
            double Tongtien = phieuxuat.getTongtien();
            Phieu ac = new Phieu(Maphieu, Thoigiantao, Nguoitao, Tongtien);
            result.add(ac);
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTietPhieu = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelTongTien = new javax.swing.JLabel();
        labelMaPhieu = new javax.swing.JLabel();
        labelNguoiTao = new javax.swing.JLabel();
        labelThoiGianTao = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnExportPDF = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi tiết phiếu");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Mã phiếu: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        tblChiTietPhieu.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        tblChiTietPhieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá bán", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tblChiTietPhieu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 782, 252));

        jLabel4.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Người tạo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 78, -1));

        jLabel5.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Thời gian tạo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        labelTongTien.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        labelTongTien.setForeground(new java.awt.Color(0, 0, 153));
        labelTongTien.setText("...đ");
        jPanel1.add(labelTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 203, -1));

        labelMaPhieu.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        labelMaPhieu.setForeground(new java.awt.Color(0, 0, 153));
        labelMaPhieu.setText("jLabel7");
        jPanel1.add(labelMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 242, -1));

        labelNguoiTao.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        labelNguoiTao.setForeground(new java.awt.Color(0, 0, 153));
        labelNguoiTao.setText("jLabel7");
        jPanel1.add(labelNguoiTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 234, -1));

        labelThoiGianTao.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        labelThoiGianTao.setForeground(new java.awt.Color(0, 0, 153));
        labelThoiGianTao.setText("jLabel7");
        jPanel1.add(labelThoiGianTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 242, -1));

        jLabel7.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("TỔNG TIỀN:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        jLabel1.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("CHI TIẾT PHIẾU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        btnExportPDF.setBackground(new java.awt.Color(0, 0, 153));
        btnExportPDF.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        btnExportPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnExportPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_pdf_25px.png"))); // NOI18N
        btnExportPDF.setText("Xuất PDF");
        btnExportPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPDFActionPerformed(evt);
            }
        });
        jPanel1.add(btnExportPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 138, 44));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/sRKbEzd.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -150, 1020, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPDFActionPerformed
        // TODO add your handling code here:
        WritePDF writepdf = new WritePDF();
        writepdf.writePhieuNhap(this.parent.findPhieu().getMaphieu());
    }//GEN-LAST:event_btnExportPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMaPhieu;
    private javax.swing.JLabel labelNguoiTao;
    private javax.swing.JLabel labelThoiGianTao;
    private javax.swing.JLabel labelTongTien;
    private javax.swing.JTable tblChiTietPhieu;
    // End of variables declaration//GEN-END:variables
}
