/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.SanphamDAO;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Sanpham;


public class DetailProduct extends javax.swing.JDialog {

    /**
     * Creates new form ThemSP
     */
    private ProductForm owner;
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    public DetailProduct(javax.swing.JInternalFrame parent, javax.swing.JFrame owner, boolean modal) {
        super(owner, modal);       
        initComponents();
        setLocationRelativeTo(null);
        this.owner = (ProductForm) parent;
Sanpham sp = this.owner.getSanphamSelect();
    if (sp != null) {
            txtMasp.setText(sp.getMasp());
            txtTensp.setText(sp.getTensp());
            txtDonvitinh.setText(sp.getDonvitinh());
            txtGianhap.setText(formatter.format(sp.getGianhap())+"đ");
            txtGiaban.setText(formatter.format(sp.getGiaban())+"đ");
            txtMancc.setText(sp.getMancc());
            dateNgaysanxuat.setDate(sp.getNgaysanxuat());
            dateHansudung.setDate(sp.getHansudung());
            txtGhichu.setText(sp.getGhichu());
            if (sp.getTrangthai() == 1) {
            cbxTrangthai.setSelectedItem("Đang bán");
        } else {
            cbxTrangthai.setSelectedItem("Ngưng bán");
        }
            txtSoluong.setText(Integer.toString(sp.getSoluong()));
        } 
            cbxLoaisp.setSelectedItem(sp.getLoaisp());
    }
    

    private DetailProduct(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMasp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTensp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDonvitinh = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtSoluong = new javax.swing.JTextField();
        txtGianhap = new javax.swing.JTextField();
        txtGiaban = new javax.swing.JTextField();
        txtMancc = new javax.swing.JTextField();
        dateNgaysanxuat = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbxLoaisp = new javax.swing.JComboBox<>();
        cbxTrangthai = new javax.swing.JComboBox<>();
        dateHansudung = new com.toedter.calendar.JDateChooser();
        txtGhichu = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm sản phẩm mới");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(19, 59, 89));
        jLabel2.setText("Mã sản phẩm");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        txtMasp.setEnabled(false);
        jPanel1.add(txtMasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 189, 32));

        jLabel3.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(19, 59, 89));
        jLabel3.setText("Tên sản phẩm");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        txtTensp.setEnabled(false);
        jPanel1.add(txtTensp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 189, 32));

        jLabel1.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(19, 59, 89));
        jLabel1.setText("THÔNG TIN SẢN PHẨM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(19, 59, 89));
        jLabel4.setText("Đơn vị tính");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, -1));

        txtDonvitinh.setForeground(new java.awt.Color(255, 255, 255));
        txtDonvitinh.setEnabled(false);
        jPanel1.add(txtDonvitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 189, 32));

        jPanel3.setLayout(new java.awt.CardLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 84, -1, -1));

        txtSoluong.setEnabled(false);
        jPanel1.add(txtSoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 189, 33));

        txtGianhap.setEnabled(false);
        jPanel1.add(txtGianhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 189, 32));

        txtGiaban.setEnabled(false);
        jPanel1.add(txtGiaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 189, 32));

        txtMancc.setForeground(new java.awt.Color(19, 59, 89));
        txtMancc.setEnabled(false);
        jPanel1.add(txtMancc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 189, 32));

        dateNgaysanxuat.setEnabled(false);
        jPanel1.add(dateNgaysanxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 200, 30));

        jLabel5.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(19, 59, 89));
        jLabel5.setText("Số lượng");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(19, 59, 89));
        jLabel7.setText("Giá bán");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 70, -1));

        jLabel6.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(19, 59, 89));
        jLabel6.setText("Giá nhập");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 90, -1));

        jLabel8.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(19, 59, 89));
        jLabel8.setText("Mã nhà cung cấp");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 140, -1));

        jLabel9.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(19, 59, 89));
        jLabel9.setText("Ngày sản xuất");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(19, 59, 89));
        jLabel11.setText("Loại sản phẩm");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(19, 59, 89));
        jLabel12.setText("Trạng thái");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(19, 59, 89));
        jLabel13.setText("Hạn sử dụng");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));

        jLabel14.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(19, 59, 89));
        jLabel14.setText("Ghi chú");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, -1));

        cbxLoaisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn loại sản phẩm--", "Thực phẩm", "Đồ gia dụng", "Mỹ phẩm", "Văn phòng phẩm", "Đồ dùng các nhân", " " }));
        cbxLoaisp.setEnabled(false);
        cbxLoaisp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLoaispItemStateChanged(evt);
            }
        });
        cbxLoaisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaispActionPerformed(evt);
            }
        });
        cbxLoaisp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxLoaispPropertyChange(evt);
            }
        });
        jPanel1.add(cbxLoaisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 200, 32));

        cbxTrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn trạng thái--", "Đang bán", "Ngưng bán" }));
        cbxTrangthai.setEnabled(false);
        jPanel1.add(cbxTrangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 200, 30));

        dateHansudung.setEnabled(false);
        jPanel1.add(dateHansudung, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 210, 30));

        txtGhichu.setEnabled(false);
        jPanel1.add(txtGhichu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 200, 30));

        jLabel16.setForeground(new java.awt.Color(51, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/open-sky-trees-shooting-stars-4k-5f-1280x800.jpg"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -270, 1090, 900));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxLoaispItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLoaispItemStateChanged

    }//GEN-LAST:event_cbxLoaispItemStateChanged

    private void cbxLoaispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaispActionPerformed

    private void cbxLoaispPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxLoaispPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaispPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetailProduct dialog = new DetailProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxLoaisp;
    private javax.swing.JComboBox<String> cbxTrangthai;
    private com.toedter.calendar.JDateChooser dateHansudung;
    private com.toedter.calendar.JDateChooser dateNgaysanxuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDonvitinh;
    private javax.swing.JTextField txtGhichu;
    private javax.swing.JTextField txtGiaban;
    private javax.swing.JTextField txtGianhap;
    private javax.swing.JTextField txtMancc;
    private javax.swing.JTextField txtMasp;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTensp;
    // End of variables declaration//GEN-END:variables
}
