/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import model.Giamgia;
import dao.GiamgiaDAO;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author hungmetan
 */
public class DetailMagiamgia extends javax.swing.JDialog {

    private MagiamgiaForm owner;
    DecimalFormat formatter = new DecimalFormat("###,###,###");
        public DetailMagiamgia(javax.swing.JInternalFrame parent, javax.swing.JFrame owner, boolean modal) {
        super(owner, modal);       
        initComponents();
        setLocationRelativeTo(null);
        this.owner = (MagiamgiaForm) parent;
Giamgia gg = this.owner.getMagiamgiaSelect();
    if (gg != null) {
            txtMagiamgia.setText(gg.getMagiamgia());
            cbxLoaisp.setSelectedItem(gg.getLoaisp());
            txtPhantramgiam.setText(Integer.toString(gg.getPhantramgiam()));
            dateNgaybatdau.setDate(gg.getNgaybatdau());
            dateNgayketthuc.setDate(gg.getNgayketthuc());
            txtMota.setText(gg.getMota());
            if (gg.getTrangthai() == 1) {
            cbxTrangthai.setSelectedItem("Khả dụng");
        } else {
            cbxTrangthai.setSelectedItem("Không khả dụng");
        }
            
        } 
           
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMagiamgia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtPhantramgiam = new javax.swing.JTextField();
        dateNgaybatdau = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbxLoaisp = new javax.swing.JComboBox<>();
        cbxTrangthai = new javax.swing.JComboBox<>();
        dateNgayketthuc = new com.toedter.calendar.JDateChooser();
        txtMota = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(19, 59, 89));
        jLabel2.setText("Mã giảm giá");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        txtMagiamgia.setEnabled(false);
        jPanel1.add(txtMagiamgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 189, 32));

        jLabel4.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(19, 59, 89));
        jLabel4.setText("THÔNG TIN MÃ GIẢM GIÁ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jPanel3.setLayout(new java.awt.CardLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 84, -1, -1));

        txtPhantramgiam.setEnabled(false);
        jPanel1.add(txtPhantramgiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 189, 33));

        dateNgaybatdau.setEnabled(false);
        jPanel1.add(dateNgaybatdau, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 200, 30));

        jLabel6.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(19, 59, 89));
        jLabel6.setText("Phần trăm giảm");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(19, 59, 89));
        jLabel10.setText("Ngày bắt đầu");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(19, 59, 89));
        jLabel11.setText("Loại sản phẩm");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(19, 59, 89));
        jLabel12.setText("Trạng thái");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(19, 59, 89));
        jLabel13.setText("Ngày kết thúc");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(19, 59, 89));
        jLabel14.setText("Mô tả");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        cbxLoaisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn loại sản phẩm--", "Thực phẩm", "Đồ gia dụng", "Mỹ phẩm", "Văn phòng phẩm", "Đồ dùng các nhân", " " }));
        cbxLoaisp.setEnabled(false);
        cbxLoaisp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLoaispItemStateChanged(evt);
            }
        });
        cbxLoaisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaispActionPerformed(evt);
            }
        });
        cbxLoaisp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxLoaispPropertyChange(evt);
            }
        });
        jPanel1.add(cbxLoaisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 200, 32));

        cbxTrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn trạng thái--", "Đang bán", "Ngưng bán" }));
        cbxTrangthai.setEnabled(false);
        jPanel1.add(cbxTrangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 200, 30));

        dateNgayketthuc.setEnabled(false);
        jPanel1.add(dateNgayketthuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 210, 30));

        txtMota.setEnabled(false);
        jPanel1.add(txtMota, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 200, 30));

        jLabel16.setForeground(new java.awt.Color(51, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/open-sky-trees-shooting-stars-4k-5f-1280x800.jpg"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -270, 820, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 763, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxLoaispItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLoaispItemStateChanged

    }//GEN-LAST:event_cbxLoaispItemStateChanged

    private void cbxLoaispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaispActionPerformed

    private void cbxLoaispPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxLoaispPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaispPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailMagiamgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailMagiamgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailMagiamgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailMagiamgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
               java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetailMagiamgia dialog = new DetailMagiamgia(null, new JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxLoaisp;
    private javax.swing.JComboBox<String> cbxTrangthai;
    private com.toedter.calendar.JDateChooser dateNgaybatdau;
    private com.toedter.calendar.JDateChooser dateNgayketthuc;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtMagiamgia;
    private javax.swing.JTextField txtMota;
    private javax.swing.JTextField txtPhantramgiam;
    // End of variables declaration//GEN-END:variables
}
