/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.SanphamDAO;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Sanpham;

public class UpdateProduct extends javax.swing.JDialog {


    private ProductForm owner;
    DecimalFormat formatterE = new DecimalFormat("0");
    
   public UpdateProduct(javax.swing.JInternalFrame parent, javax.swing.JFrame owner, boolean modal) {
    super(owner, modal);
    this.owner = (ProductForm) parent;
    initComponents();
    setLocationRelativeTo(null);

    // Lấy sản phẩm đang chọn từ ProductForm
    Sanpham sp = this.owner.getSanphamSelect();
    if (sp != null) {
        txtMasp.setText(sp.getMasp());
        txtTensp.setText(sp.getTensp());
        txtDonvitinh.setText(sp.getDonvitinh());
        txtSoluong.setText(String.valueOf(sp.getSoluong()));
        txtGianhap1.setText(String.valueOf(sp.getGianhap()));
        txtGiaban.setText(String.valueOf(sp.getGiaban()));
        txtMancc.setText(sp.getMancc());
        dateNgaysanxuat.setDate(sp.getNgaysanxuat());
        dateHansudung.setDate(sp.getHansudung());
        txtGhichu.setText(sp.getGhichu());

        // Gán giá trị cho ComboBox loại sản phẩm
        cbxLoaisp1.setSelectedItem(sp.getLoaisp());

        // Gán giá trị cho ComboBox trạng thái
        if (sp.getTrangthai() == 1) {
            cbxTrangthai.setSelectedItem("Đang bán");
        } else {
            cbxTrangthai.setSelectedItem("Ngưng bán");
        }
    }
}


    private UpdateProduct(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGianhap = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMasp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTensp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDonvitinh = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtSoluong = new javax.swing.JTextField();
        txtGianhap1 = new javax.swing.JTextField();
        txtGiaban = new javax.swing.JTextField();
        txtMancc = new javax.swing.JTextField();
        dateNgaysanxuat = new com.toedter.calendar.JDateChooser();
        cbxLoaisp1 = new javax.swing.JComboBox<>();
        cbxTrangthai = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        dateHansudung = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtGhichu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chỉnh sửa sản phẩm");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(194, 248, 248));
        jLabel2.setText("Mã sản phẩm");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        txtMasp.setEditable(false);
        txtMasp.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtMasp.setRequestFocusEnabled(false);
        jPanel1.add(txtMasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 189, 30));

        jLabel3.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(194, 248, 248));
        jLabel3.setText("Tên sản phẩm");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        txtTensp.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtTensp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 189, 30));

        jLabel4.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(194, 248, 248));
        jLabel4.setText("Số lượng");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 82, -1));

        txtDonvitinh.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtDonvitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 189, 30));

        btnAddProduct.setBackground(new java.awt.Color(194, 248, 248));
        btnAddProduct.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(51, 0, 102));
        btnAddProduct.setText("Lưu thay đổi");
        btnAddProduct.setBorder(null);
        btnAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 140, 35));

        btnCancel.setBackground(new java.awt.Color(194, 248, 248));
        btnCancel.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(51, 0, 102));
        btnCancel.setText("Huỷ bỏ");
        btnCancel.setBorder(null);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 140, 35));

        jPanel3.setLayout(new java.awt.CardLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 89, 186, -1));

        txtSoluong.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtSoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 189, 30));
        jPanel1.add(txtGianhap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 189, 32));
        jPanel1.add(txtGiaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 189, 30));
        jPanel1.add(txtMancc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 189, 32));
        jPanel1.add(dateNgaysanxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 200, 30));

        cbxLoaisp1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn loại sản phẩm--", "Thực phẩm", "Đồ gia dụng", "Mỹ phẩm", "Văn phòng phẩm", "Đồ dùng các nhân", " " }));
        cbxLoaisp1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLoaisp1ItemStateChanged(evt);
            }
        });
        cbxLoaisp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaisp1ActionPerformed(evt);
            }
        });
        cbxLoaisp1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxLoaisp1PropertyChange(evt);
            }
        });
        jPanel1.add(cbxLoaisp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 209, 32));

        cbxTrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn trạng thái--", "Đang bán", "Ngưng bán" }));
        jPanel1.add(cbxTrangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 210, 30));

        jLabel12.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(194, 248, 248));
        jLabel12.setText("Trạng thái");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));
        jPanel1.add(dateHansudung, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 210, 30));

        jLabel1.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(194, 248, 248));
        jLabel1.setText("Hạn sử dụng");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));
        jPanel1.add(txtGhichu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 210, 30));

        jLabel5.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(194, 248, 248));
        jLabel5.setText("CẬP NHẬT THÔNG TIN SẢN PHẨM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(194, 248, 248));
        jLabel13.setText("Ghi chú");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(194, 248, 248));
        jLabel11.setText("Loại sản phẩm");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(194, 248, 248));
        jLabel9.setText("Ngày sản xuất");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(194, 248, 248));
        jLabel8.setText("Mã nhà cung cấp");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 150, -1));

        jLabel7.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(194, 248, 248));
        jLabel7.setText("Giá bán");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 70, -1));

        jLabel6.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(194, 248, 248));
        jLabel6.setText("Giá nhập");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 80, -1));

        jLabel16.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(194, 248, 248));
        jLabel16.setText("Đơn vị tính");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 90, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/wallpapersden.com_town-8-bit_3840x2160 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -180, 1370, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        String Masp = txtMasp.getText().trim();
        String Tensp = txtTensp.getText().trim();
        String Donvitinh = txtDonvitinh.getText().trim();
        String SoluongStr = txtSoluong.getText().trim();
        String GianhapStr = txtGianhap1.getText().trim();
        String GiabanStr = txtGiaban.getText().trim();
        String Mancc = txtMancc.getText().trim();
        Date Ngaysanxuat = dateNgaysanxuat.getDate();
        String Loaisp = cbxLoaisp1.getSelectedItem().toString();
        String TrangthaiStr = cbxTrangthai.getSelectedItem().toString();
        Date Hansudung= dateHansudung.getDate(); 
      
        //Kiểm tra rỗng
         if (Masp.isEmpty() || Tensp.isEmpty() || Donvitinh.isEmpty() ||
        SoluongStr.isEmpty() || GianhapStr.isEmpty() || GiabanStr.isEmpty() ||
        Mancc.isEmpty() || Ngaysanxuat == null || Hansudung == null ||
        Loaisp.equals("--Chọn loại sản phẩm--") ||
        TrangthaiStr.equals("--Chọn trạng thái--")) {

        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin !");
        return;
    }
         //Kiểm tra kiểu dữ liệu
        int Soluong = 0;
        double Gianhap = 0;
        double Giaban = 0;
        try {
        Soluong = Integer.parseInt(SoluongStr);
        Gianhap = Double.parseDouble(GianhapStr);
        Giaban = Double.parseDouble(GiabanStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Số lượng và giá phải ở dạng số hợp lệ!");
        return;
    }
        int Trangthai = TrangthaiStr.equals("Đang bán") ? 1 : 0;
        String Ghichu = txtGhichu.getText().trim();          
         // Cập nhật đối tượng sản phẩm
    Sanpham sp = new Sanpham(Masp, Tensp, Donvitinh, Soluong, Gianhap, Giaban, Ngaysanxuat, Hansudung,Loaisp, Mancc,Trangthai,Ghichu );
                // Cập nhật DB
    int result = SanphamDAO.getInstance().update(sp);
    if (result > 0) {
        JOptionPane.showMessageDialog(this, "Sửa sản phẩm thành công!");
        owner.loadDataToTable();
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Sửa sản phẩm thất bại!");
    }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void cbxLoaisp1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLoaisp1ItemStateChanged

    }//GEN-LAST:event_cbxLoaisp1ItemStateChanged

    private void cbxLoaisp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaisp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaisp1ActionPerformed

    private void cbxLoaisp1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxLoaisp1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaisp1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateProduct dialog = new UpdateProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cbxLoaisp1;
    private javax.swing.JComboBox<String> cbxTrangthai;
    private com.toedter.calendar.JDateChooser dateHansudung;
    private com.toedter.calendar.JDateChooser dateNgaysanxuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDonvitinh;
    private javax.swing.JTextField txtGhichu;
    private javax.swing.JTextField txtGiaban;
    private javax.swing.JTextField txtGianhap;
    private javax.swing.JTextField txtGianhap1;
    private javax.swing.JTextField txtMancc;
    private javax.swing.JTextField txtMasp;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTensp;
    // End of variables declaration//GEN-END:variables
}
