/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import dao.GiamgiaDAO;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Giamgia;
/**
 *
 * @author hungmetan
 */
public class UpdateMagiamgia extends javax.swing.JDialog {
    
private MagiamgiaForm owner;
   
    public UpdateMagiamgia(javax.swing.JInternalFrame parent, javax.swing.JFrame owner, boolean modal) {
        super(owner, modal);
        this.owner = (MagiamgiaForm) parent;
        initComponents();
        setLocationRelativeTo(null);
        Giamgia gg = this.owner.getMagiamgiaSelect(); 
        if (gg != null) {
        txtMagiamgia.setText(gg.getMagiamgia());
        cbxLoaisp.setSelectedItem(gg.getLoaisp());
        txtPhantramgiam.setText(String.valueOf(gg.getPhantramgiam()));
        dateNgaybatdau.setDate(gg.getNgaybatdau());
        dateNgayketthuc.setDate(gg.getNgayketthuc());
        txtMota.setText(gg.getMota());
        if (gg.getTrangthai() == 1) {
            cbxTrangthai.setSelectedItem("Khả dụng");
        } else {
            cbxTrangthai.setSelectedItem("Không khả dụng");
        }
    }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMota = new javax.swing.JTextField();
        txtMagiamgia = new javax.swing.JTextField();
        txtPhantramgiam = new javax.swing.JTextField();
        dateNgaybatdau = new com.toedter.calendar.JDateChooser();
        dateNgayketthuc = new com.toedter.calendar.JDateChooser();
        cbxTrangthai = new javax.swing.JComboBox<>();
        cbxLoaisp = new javax.swing.JComboBox<>();
        btnAddMagiamgia = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(194, 248, 248));
        jLabel5.setText("CẬP NHẬT MÃ GIẢM GIÁ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(194, 248, 248));
        jLabel2.setText("Mã giảm giá");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(194, 248, 248));
        jLabel4.setText("Phần trăm giảm");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 130, -1));

        jLabel9.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(194, 248, 248));
        jLabel9.setText("Ngày bắt đầu");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(194, 248, 248));
        jLabel11.setText("Loại sản phẩm");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(194, 248, 248));
        jLabel12.setText("Trạng thái");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(194, 248, 248));
        jLabel3.setText("Ngày kết thúc");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(194, 248, 248));
        jLabel13.setText("Mô tả");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));
        getContentPane().add(txtMota, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 180, 30));
        getContentPane().add(txtMagiamgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 180, 30));

        txtPhantramgiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhantramgiamActionPerformed(evt);
            }
        });
        getContentPane().add(txtPhantramgiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 180, 30));
        getContentPane().add(dateNgaybatdau, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 200, -1));
        getContentPane().add(dateNgayketthuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 200, -1));

        cbxTrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn trạng thái--", "Khả dụng", "Không khả dụng" }));
        getContentPane().add(cbxTrangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 190, 30));

        cbxLoaisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn loại sản phẩm--", "Thực phẩm", "Đồ gia dụng", "Mỹ phẩm", "Văn phòng phẩm", "Đồ dùng các nhân", " " }));
        getContentPane().add(cbxLoaisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 190, 30));

        btnAddMagiamgia.setBackground(new java.awt.Color(194, 248, 248));
        btnAddMagiamgia.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        btnAddMagiamgia.setForeground(new java.awt.Color(51, 0, 102));
        btnAddMagiamgia.setText("Lưu thay đổi");
        btnAddMagiamgia.setBorder(null);
        btnAddMagiamgia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddMagiamgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMagiamgiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddMagiamgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 140, 35));

        btnCancel.setBackground(new java.awt.Color(194, 248, 248));
        btnCancel.setFont(new java.awt.Font("#9Slide03 Saira SemiCondensed SemiBold", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(51, 0, 102));
        btnCancel.setText("Huỷ bỏ");
        btnCancel.setBorder(null);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 140, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/wallpapersden.com_town-8-bit_3840x2160 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 463));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhantramgiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhantramgiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhantramgiamActionPerformed

    private void btnAddMagiamgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMagiamgiaActionPerformed
        // TODO add your handling code here:
        String Magiamgia = txtMagiamgia.getText().trim();
        String Loaisp = cbxLoaisp.getSelectedItem().toString();
        String PhantramgiamStr = txtPhantramgiam.getText().trim();
        Date Ngaybatdau = dateNgaybatdau.getDate();
        Date Ngayketthuc= dateNgayketthuc.getDate();
        String Mota = txtMota.getText().trim();
        String TrangthaiStr = cbxTrangthai.getSelectedItem().toString();
              
     

        //Kiểm tra rỗng
        if (Magiamgia.isEmpty() || Loaisp.equals("--Chọn loại sản phẩm--") || PhantramgiamStr.isEmpty() ||
             Ngaybatdau == null || Ngayketthuc == null||
            Mota.isEmpty() || TrangthaiStr.equals("--Chọn trạng thái--")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin !");
            return;
        }
        //Kiểm tra kiểu dữ liệu
        int Phantramgiam = 0;

        try {
          Phantramgiam = Integer.parseInt(PhantramgiamStr);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Phần trăm giảm phải ở dạng số hợp lệ!");
            return;
        }
        int Trangthai = TrangthaiStr.equals("Khả dụng") ? 1 : 0;
        // Cập nhật đối tượng sản phẩm
        Giamgia sp = new Giamgia(Magiamgia, Loaisp, Phantramgiam, Ngaybatdau, Ngayketthuc, Mota, Trangthai );
        // Cập nhật DB
        int result = GiamgiaDAO.getInstance().update(sp);
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Sửa mã giảm giá thành công!");
            owner.loadDataToTable();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa mã giảm giá thất bại!");
        }
    }//GEN-LAST:event_btnAddMagiamgiaActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMagiamgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMagiamgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMagiamgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMagiamgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateMagiamgia dialog = new UpdateMagiamgia(null, new JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMagiamgia;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cbxLoaisp;
    private javax.swing.JComboBox<String> cbxTrangthai;
    private com.toedter.calendar.JDateChooser dateNgaybatdau;
    private com.toedter.calendar.JDateChooser dateNgayketthuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtMagiamgia;
    private javax.swing.JTextField txtMota;
    private javax.swing.JTextField txtPhantramgiam;
    // End of variables declaration//GEN-END:variables
}
